import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { getMatchesfootball, getMatchesfootballFinished } from "@/api";
import Navbar from "@/components/Navbar";
import News from "@/components/News";
import Dwris from "@/components/Dwris";
import Status from "@/components/Status";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Football info",
  description: "Generated by create next app",
};
const getDatas = await getMatchesfootball();
const getDatasFinished = await getMatchesfootballFinished();

const matchesDatas = getDatas?.matches;
const matchesDatasFinished = getDatasFinished?.matches;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="px-2 py-2 md:px-16 md:py-4 text-textPrimary">
          <Navbar />

          <section className="flex flex-col md:flex-row md:space-x-4 space-y-4 md:space-y-0">
            <Status
              matchesList={matchesDatas}
              matchesListFinished={matchesDatasFinished}
            />
            <Dwris />
            <div className="flex-1">
              {children}
              <News />
            </div>
          </section>
        </main>
      </body>
    </html>
  );
}
