import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import News from "@/components/News";
import Dwris from "@/components/Dwris";
import Status from "@/components/Status";
import { getMatchesfootball, getMatchesfootballFinished } from "@/api";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nova Matches | نوفا ماتش",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // جلب البيانات هنا داخل المكون
  const getDatas = await getMatchesfootball();
  const getDatasFinished = await getMatchesfootballFinished();

  const matchesDatas = getDatas?.matches;
  const matchesDatasFinished = getDatasFinished?.matches;

  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2365434402623559"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className={inter.className}>
        <main className="px-2 py-2 md:px-16 md:py-4 text-textPrimary">
          <Navbar />
          <section className="flex flex-col md:flex-row md:space-x-4 space-y-4 md:space-y-0">
            <Status
              matchesList={matchesDatas}
              matchesListFinished={matchesDatasFinished}
            />
            <Dwris />
            <div className="flex-1">
              {children}
              <News />
            </div>
          </section>
        </main>
      </body>
    </html>
  );
}
