import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { filterLeague } from "@/api";
import LeagueTable from "@/components/LeagueTable";
import Navbar from "@/components/Navbar";
import News from "@/components/News";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Football info",
  description: "Generated by create next app",
};

async function fetchLeagues() {
  const getLaLiga = await filterLeague("Primera Division");
  const getEnglishLeague = await filterLeague("Premier League");
  const getBundesliga = await filterLeague("Bundesliga");
  const getChampionship = await filterLeague("Championship");
  const getCopaLibertadores = await filterLeague("Copa Libertadores");
  const getLigue1 = await filterLeague("Ligue 1");
  const getPrimeiraLiga = await filterLeague("Primeira Liga");
  const getSerieA = await filterLeague("Serie A");
  const getBrasileiro = await filterLeague("Campeonato Brasileiro Série A");

  return {
    getLaLiga,
    getEnglishLeague,
    getBundesliga,
    getChampionship,
    getCopaLibertadores,
    getLigue1,
    getPrimeiraLiga,
    getSerieA,
    getBrasileiro,
  };
}

const LeagueSection = ({ title, data }: { title: string; data: any[] }) => (
  <section>
    <h2 className="text-xl font-bold mb-4">{title}</h2>
    <div className="w-[600px]">
      {data.map((team) => (
        <div key={team.id}>
          <LeagueTable data={team} />
        </div>
      ))}
    </div>
  </section>
);

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {
    getLaLiga,
    getEnglishLeague,
    getBundesliga,
    getChampionship,
    getCopaLibertadores,
    getLigue1,
    getPrimeiraLiga,
    getSerieA,
    getBrasileiro,
  } = await fetchLeagues();

  return (
    <html lang="en">
      <body className={inter.className}>
        <br />
        <main className="px-2 md:px-16 md:py-2 text-textPrimary">
          <Navbar />
          {children}
          <p>
            ________________________________________________________________________________
          </p>
          <LeagueSection title="La Liga" data={getLaLiga} />
          <p>
            ________________________________________________________________________________
          </p>
          <LeagueSection title="Premier League" data={getEnglishLeague} />
          <p>
            ________________________________________________________________________________
          </p>
          <LeagueSection title="Bundesliga" data={getBundesliga} />
          <p>
            ________________________________________________________________________________
          </p>
          <LeagueSection title="Championship" data={getChampionship} />
          <p>
            ________________________________________________________________________________
          </p>
          <LeagueSection title="Copa Libertadores" data={getCopaLibertadores} />
          <p>
            ________________________________________________________________________________
          </p>
          <LeagueSection title="Ligue 1" data={getLigue1} />
          <p>
            ________________________________________________________________________________
          </p>
          <LeagueSection title="Primeira Liga" data={getPrimeiraLiga} />
          <p>
            ________________________________________________________________________________
          </p>
          <LeagueSection title="Serie A" data={getSerieA} />
          <p>
            ________________________________________________________________________________
          </p>
          <LeagueSection
            title="Campeonato Brasileiro Série A"
            data={getBrasileiro}
          />

          <section className="flex space-x-4">
            <News />
          </section>
        </main>
      </body>
    </html>
  );
}
